[package]
name = "shared"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
moonlight.workspace = true
serde = { version = "1.0.152", features = ["derive"] }

[features]
frontend = ["moonlight/frontend"]
backend = ["moonlight/backend"]
