[package]
name = "shared"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
moonlight.workspace = true
rspotify = {git = "https://github.com/ramsayleung/rspotify" }

[features]
frontend = ["moonlight/frontend"]
backend = ["moonlight/backend"]
