name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with: 
        toolchain: stable
        target: wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "20.04"
    - name: Install mzoon
      run: cargo install mzoon --git https://github.com/MoonZoon/MoonZoon --locked
    - name: Build
      run: mzoon build -r
    - name: Create build
      run: |
        mkdir ./build
        mv ./target/release/backend ./build/backend
        chmod +x ./build/backend
        mv ./frontend ./build/frontend
        mv ./public ./build/public
    - name: Create .env
      uses: SpicyPizza/create-envfile@v1.3
      with: 
        envkey_REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
        envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        envkey_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        envkey_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        directory: ./build
        file_name: .env
        fail_on_empty: false
    # Upload Artifact
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          ./build
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
