name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with: 
        toolchain: stable
        target: wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "20.04"
    - name: Install mzoon
      run: cargo install mzoon --git https://github.com/MoonZoon/MoonZoon --locked
    - name: Build
      run: mzoon build -r
    # Upload Artifact
    - name: Upload production-ready build files
      uses: actions/upload-artifact@v3
      with:
        name: production
        path: |
          ./target/release/backend
          ./frontend
          ./public
